In [1]:
import pandas as pd

In [2]:
messages=pd.read_csv('SMSSpamCollection.txt',sep='\t',names=["label","message"])

In [3]:
messages

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [4]:
## Data Cleaning and Preprocessing

import re
import nltk
nltk.download('all')

[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to
[nltk_data]    |     C:\Users\ashish\AppData\Roaming\nltk_data...
[nltk_data]    |   Package abc is already up-to-date!
[nltk_data]    | Downloading package alpino to
[nltk_data]    |     C:\Users\ashish\AppData\Roaming\nltk_data...
[nltk_data]    |   Package alpino is already up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     C:\Users\ashish\AppData\Roaming\nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_eng to
[nltk_data]    |     C:\Users\ashish\AppData\Roaming\nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_eng is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     C:\Users\ashish\AppData\Roaming\nltk_data

True

In [5]:
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
lematizer=WordNetLemmatizer()

In [6]:

messages['message'][0]

'Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'

In [7]:
corpus=[]
for i in range(0,len(messages)):
    review=re.sub('[^a-zA-z]',' ',messages['message'][i])
    review=review.lower()
    review=review.split()
    review=[lematizer.lemmatize(word,pos='v') for word in review if not word in stopwords.words('english')]
    review=' '.join(review)
    corpus.append(review)

In [8]:
len(corpus)

5572

## Create Bag of Words 

In [9]:
from sklearn.feature_extraction.text import CountVectorizer
##  for binary BOW enable binary=True

cv=CountVectorizer(max_features=100,binary=True) # max_feature means here is that if we sort the vocabolary in descinding order and then select the top n words based on frequency



In [10]:
X=cv.fit_transform(corpus).toarray()

In [11]:

X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [12]:

import numpy as np
np.set_printoptions(edgeitems=30, linewidth=100000, 
    formatter=dict(float=lambda x: "%.3g" % x))
X

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0

### N-Grams

In [13]:
cv.vocabulary_

{'go': 24,
 'great': 26,
 'get': 22,
 'wat': 91,
 'ok': 58,
 'free': 21,
 'win': 95,
 'text': 79,
 'txt': 86,
 'say': 68,
 'already': 0,
 'think': 81,
 'hey': 29,
 'week': 93,
 'back': 4,
 'like': 40,
 'still': 75,
 'send': 70,
 'even': 18,
 'prize': 64,
 'claim': 9,
 'call': 6,
 'mobile': 49,
 'home': 31,
 'want': 90,
 'today': 83,
 'cash': 8,
 'day': 15,
 'reply': 66,
 'www': 97,
 'right': 67,
 'thank': 80,
 'take': 77,
 'time': 82,
 'use': 88,
 'message': 47,
 'com': 10,
 'oh': 57,
 'yes': 99,
 'make': 45,
 'way': 92,
 'feel': 19,
 'dont': 17,
 'miss': 48,
 'ur': 87,
 'try': 85,
 'da': 14,
 'lor': 42,
 'meet': 46,
 'really': 65,
 'know': 35,
 'lol': 41,
 'leave': 38,
 'love': 43,
 'let': 39,
 'work': 96,
 'wait': 89,
 'yeah': 98,
 'tell': 78,
 'anything': 1,
 'please': 62,
 'msg': 51,
 'see': 69,
 'pls': 63,
 'need': 53,
 'tomorrow': 84,
 'hope': 32,
 'well': 94,
 'lt': 44,
 'gt': 27,
 'ask': 2,
 'keep': 34,
 'morning': 50,
 'happy': 28,
 'sorry': 73,
 'give': 23,
 'new': 54,
 'find

In [14]:
## Create the Bag of Words with ngram
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=100,binary=True,ngram_range=(2,3))
X=cv.fit_transform(corpus).toarray()

In [15]:
cv.vocabulary_

{'free entry': 33,
 'claim call': 18,
 'call claim': 3,
 'free call': 32,
 'chance win': 17,
 'txt word': 91,
 'let know': 54,
 'go home': 36,
 'please call': 68,
 'lt gt': 60,
 'want go': 97,
 'like lt': 55,
 'like lt gt': 56,
 'sorry call': 83,
 'call later': 11,
 'sorry call later': 84,
 'ur award': 92,
 'come back': 23,
 'call customer': 4,
 'customer service': 25,
 'cash prize': 16,
 'call customer service': 5,
 'po box': 71,
 'try contact': 89,
 'draw show': 29,
 'show prize': 81,
 'prize guarantee': 75,
 'guarantee call': 42,
 'valid hrs': 95,
 'draw show prize': 30,
 'show prize guarantee': 82,
 'prize guarantee call': 76,
 'select receive': 78,
 'private account': 72,
 'account statement': 0,
 'call identifier': 6,
 'identifier code': 48,
 'code expire': 22,
 'private account statement': 73,
 'call identifier code': 7,
 'identifier code expire': 49,
 'urgent mobile': 94,
 'call landline': 10,
 'wat time': 98,
 'ur mob': 93,
 'gud ni': 44,
 'send stop': 80,
 'get back': 35,
 'c

In [16]:
X

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0